### ISSUE TITLE
Not updated to latest discord.py version

### ISSUE THREAD

**Issue by kokiwixx** [HyperNebula/Cookie-Bot#3]
hello ! My error :

Bot logged in as
Username: Botfee2
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\wowko\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\wowko\Desktop\Cookie-Bot-master\CookieBotV3.py", line 189, in on_ready
    print('Id: ' + bot.user.id)
TypeError: can only concatenate str (not "int") to str

**Comment by HyperNebula** [comment]
Since discord.py has updated to v1.0 and beyond that, there have been several changes to it that I'll have to add. For now, the Cookie-Bot should still run with python 3.6 installed and an older version of discord.py such as v0.16.12

I'll work on updating the bot to the latest version of discord.py, and then release it

**Comment by HyperNebula** [comment]
I have updated the bot and the latest version should now work with latest versions of discord.py

[Here's a download for the version that should work](https://github.com/HyperNebula/Cookie-Bot/releases/download/v3.1/v3.1-PythonFiles.zip)

**Comment by kokiwixx** [comment]
thank bro good job

**Comment by kokiwixx** [comment]
would you have a message system erased by the bot? 
here is my code:

```
await asyncio.sleep(4)
await bot.delete_message(ctx.message)
```
it removes only user messages. I would like him to also delete his own message.
as well as the embed

thank

**Comment by HyperNebula** [comment]
You need to first assign the message sent by the bot to a variable, and you can then delete the message using that variable.

To do it in the latest versions of discord.py you would do:
`message = await ctx.send("Hello!")
await message.delete()`

You can then also delete the user's message if you like.
